[build]
  publish = "build"
  command = "yarn build"

[[redirects]]
  from = "https://midi.netlify.com/*"
  to = "https://midi.blesswinsamuel.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
